#!/usr/bin/env python3

from mfi import MPower

if sys.version_info >= (3,0):
    import asyncio
    from resource_py3 import Py3PollWhileTrue as wait_while_true
else:
    import trollius as asyncio
    from resource_py2 import Py2PollWhileTrue as wait_while_true

if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument('address', help="address", default="localhost", nargs="?")
    parser.add_argument('port', help="port", default=7682, nargs="?")
    parser.add_argument('username', help='username', default='ubnt', nargs="?")
    parser.add_argument('pwd', help='password', default='ubnt', nargs="?")
    parser.add_argument('--on', help='toggle output', action="store_true")
    parser.add_argument('--off', help='toggle output off', action="store_true")
    parser.add_argument('--output', help='output index', type=int, default=1)
    parser.add_argument('--num_outputs', help='number of outlets', type=int, default=8)

    args = parser.parse_args()

    mFI = MPower(args.address, args.port, args.username, args.pwd)

    outputs = []


    def output_changed(value):
        print("output {} changed to {}".format(sender.index, value))


    def outputs_changed(num_outputs):
        print("number of outputs: {}".format(num_outputs))

        for o in mFI.outputs:
            if not o in outputs:
                outputs.append(o)
                o.output_changed.connect(output_changed)

    mFI.num_outputs_changed.connect(outputs_changed)


    def connected():
        if args.on:
            mFI.set_output(args.output, True)
        elif args.off:
            mFI.set_output(args.output, False)

    mFI.setOpenHandler(connected)


    @asyncio.coroutine
    def do_command():

        output = None

        def has_output:
            return not mFI.output(args.output)

        wait_while_true(has_output, 0.1)

        output = mFI.output(args.output)

        if args.on:
            mFI.set_output(args.output, True)
        elif args.off:
            mFI.set_output(args.output, False)


        def output_ready():
            return not output.ready


        wait_while_true(output_ready, 0.1)


        def not_output():
            return not output.output


        def not_off():
            return output.output == True


        def run_print_power():
            print("power usage: {}W".format(output.power))
            return True


        if args.on:
            wait_while_true(not_output, 0.1)
        elif args.off:
            wait_while_true(not_off, 0.1)
        else:
            wait_while_true(run_print_power, 10)


    asyncio.get_event_loop().run_until_complete(do_command())
